name: Pytest and Pylint
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Run pylint
      run: |
        pipenv run pylint life_expectancy
          
    - name: Run pytest
      run: |
        pipenv run pytest life_expectancy tests/
